workflows:
  version: 2
  build-django-and-react:
    jobs:
      - prepare
      - build:
          requires:
            - prepare
      - build-django:
          requires:
            - build

jobs:
  prepare:
    working_directory: ~/React-GraphQL-Songs/react-tracks-client
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          path: ~/React-GraphQL-Songs
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  build:
    working_directory: ~/React-GraphQL-Songs/react-tracks-client
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          path: ~/React-GraphQL-Songs
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build

  build-django:
    working_directory: ~/React-GraphQL-Songs/app
    docker:
      - image: circleci/python:3.8
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: ""
    steps:
      - checkout:
          path: ~/React-GraphQL-Songs
      - restore_cache:
          keys:
            - pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
            pipenv run python manage.py migrate
            pipenv run python manage.py collectstatic --noinput

      - save_cache:
          paths:
            - ~/.local/share/virtualenvs/venv # this path depends on where pipenv creates a virtualenv
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
