version: 2
jobs:
  build:
    working_directory: ~/React-GraphQL-Songs/app
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout:
          path: ~/React-GraphQL-Songs
      - restore_cache:
          keys:
            - pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - pip-packages-v1-{{ .Branch }}-
            - pip-packages-v1-
      - run:
          command: |
            sudo pip install pipenv
            pipenv shell
            pipenv install
      - run:
          command: pipenv run python manage.py runserver
          background: true
      - save_cache:
          paths:
            - ~/.local/share/virtualenvs/venv # this path depends on where pipenv creates a virtualenv
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
