version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - pip-packages-v1-{{ .Branch }}-
            - pip-packages-v1-
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          paths:
            - ~/.local/share/virtualenvs/venv # this path depends on where pipenv creates a virtualenv
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
